# This is a workflow to build MusicFormats and create an artifact of it

name: Build Ubuntu Version

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build MusicFormats for Ubuntu
        run: cd build ; cmake . ; cd .. ; make -C build

#       - name: Build LaTeX document
#         on: [push]
#         jobs:
#           build_latex:
#             runs-on: ubuntu-latest
#             steps:
# #             - name: Set up Git repository
# #               uses: actions/checkout@v2
#               - name: Compile LaTeX document
#                 uses: repaction/texlive@main
#                 with:
#                   tex_files: |
#                     documentation/mfuserguide/MusicFormatsUserGuide.tex
#
      - name: Upload libraries and executables for Ubuntu
        uses: actions/upload-artifact@v3
        with:
          name: musicformats-ubuntu-artifact
          path: |
            MusicFormatsVersionNumber.txt
            MusicFormatsVersionDate.txt
            build/bin
            build/lib
            documentation/IntroductionToMusicXML/IntroductionToMusicXML.pdf
            documentation/mfuserguide/MusicFormatsUserGuide.pdf
            documentation/mfmaintainanceguide/MusicFormatsFigures.pdf
            documentation/mfmaintainanceguide/MusicFormatsMaintainanceGuide.pdf
            documentation/mfapiguide/MusicFormatsAPIGuide.pdf
#
#             uncomment to have the full libdir in the .zip archive
#             build/libdir
