# This is a workflow to build the MusicFormats documentation and create an artifact of it

name: Build the MusicFormats documentation

# runs:
#   using: 'node20'
#   main: 'main.js'

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile-user-guide:
    name:    Compile user guide
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name:              Compile user guide
        uses:              xu-cheng/latex-action@v3
        working_directory: ./documentation
        with:
          root_file: foo.tex
#           root_file: MusicFormatsUserGuide.tex

      - name: Upload user guide
        uses: actions/upload-artifact@v4
        with:
          name: musicformats-documentation-artifact
          path: foo.pdf
#           path: MusicFormatsUserGuide.pdf
          retention-days: 1
