# This is a workflow to build MusicFormats and create an artifact of it

name: Build MacOS latest Version

# runs:
#   using: 'node20'
#   main: 'main.js'

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build MusicFormats for MacOS
        run:
#           shell: bash FOO
#           working-directory: build
          cd build; cmake -build .
#           cd build ; cmake --build .

#       - name: Setup TeX Live
#         uses: teatimeguest/setup-texlive-action@v3
#         with:
#           packages: >-
#             scheme-basic
#             hyperref
#
#       - name: Check `tlmgr` version
#         run: tlmgr --version
#
#       - name: Compile LaTeX documentation
#         uses: repaction/texlive@main
#         with:
#           tex_files: |
#             documentation/IntroductionToMusicXML/IntroductionToMusicXML.tex
#             documentation/mfuserguide/MusicFormatsUserGuide.tex
#             documentation/mfmaintainanceguide/MusicFormatsFigures.tex
#             documentation/mfmaintainanceguide/MusicFormatsMaintainanceGuide.tex
#             documentation/mfapiguide/MusicFormatsAPIGuide.tex

      - name: Upload libraries and executables for MacOS
        uses: actions/upload-artifact@v3
        with:
          name: musicformats-macos-latest-artifact
          path: |
            MusicFormatsVersionNumber.txt
            MusicFormatsVersionDate.txt
            build/bin
            build/lib
            build/Makefile
#             documentation/IntroductionToMusicXML/IntroductionToMusicXML.pdf
#             documentation/mfuserguide/MusicFormatsUserGuide.pdf
#             documentation/mfmaintainanceguide/MusicFormatsFigures.pdf
#             documentation/mfmaintainanceguide/MusicFormatsMaintainanceGuide.pdf
#             documentation/mfapiguide/MusicFormatsAPIGuide.pdf
#
#             uncomment to have the full libdir in the .zip archive
#             build/libdir
