# This is a workflow to build MusicFormats and create an artifact of it

name: Build Windows latest Version

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name:    Build library
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Build MusicFormats for Windows
        run:
          cd build ; uname -a ; cmake -G "Unix Makefiles" ; cmake -S . -B . . ; ls . ; make ; ls .


      - name: Upload libraries and executables for Windows
        uses: actions/upload-artifact@v4
        with:
          name: musicformats-windows-latest-artifact
          path: |
            MusicFormatsVersionNumber.txt
            MusicFormatsVersionDate.txt
            build/bin
            build/lib
            build/Makefile
