name: Test zauguin TeXLive installer 2
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "texlive"
  texlive:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install TeX Live
        uses: zauguin/install-texlive@v4
        with:
          packages: >
            l3build latex latex-bin luatex latex-bin-dev pdflatex

      - name: Use TeX Live
        run:
#           shell: bash
#           working-directory: build
#           echo $PATH
          pdflatex documentation/mfapiguide/MusicFormatsAPIGuide.tex
