name: Test zauguin TeXLive installer 2
on:
  push:

jobs:
  texlive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            l3build latex latex-bin luatex latex-bin-dev
            ...
      - name: Use TeX Live
        run:
          shell: bash
#           working-directory: build
          echo $PATH; pdflatex documentation/mfapiguide/MusicFormatsAPIGuide.tex
